#import "../common.typ": *
== Detector Optimization

Achieving stable operating conditions conducive to precise rare-event data collection required a comprehensive, multi-month optimization campaign following the initial CUORE cooldown. Tuning the detector's working conditions was as complex as the physical assembly of the experiment itself. The initial priority was the reduction of external noise and the stabilization of the cryogenic temperatures. This was followed by evaluating the load curves to define the optimal bolometer Working Points (WPs), and ultimately concluded with the configuration of the electronic and trigger parameters. Only after the environmental noise was mitigated and the detector parameters tuned to maximize the Signal-to-Noise Ratio (SNR) could the final triggering algorithms and thresholds be reliably established.

=== Noise Reduction

The extreme thermal sensitivity of the CUORE bolometers inherently renders them highly susceptible to external perturbations, including mechanical vibrations, electrical noise, and micro-seismic events such as distant earthquakes or operations within the underground laboratory. The immediate priority during the initial optimization phase was the elimination of ground loops and mechanical vibrations. Significant effort was dedicated to electrically isolating the detector systems and associated room-temperature electronics from the external environment.

Concurrently, all cryogenics-related sources of mechanical vibration—predominantly originating from the Pulse Tube (PT) cryocoolers and the cryostat support structure itself—were systematically mapped. These were mitigated through mechanical means as described in sec#footnote[which?], as well as more dynamic methods described here.

Specific noise sources were diagnosed by analyzing the noise power spectra of the detectors (Refer to @sec4.2-pipeline for details about noise power spectrum construction). By analyzing the noise, the collaboration could identify and isolate distinct noise peaks overlapping with the bolometer signal bandwidth, notably vibratoins induced by the PTs and the lower-frequency resonances associated with the detector suspension system.

==== Pulse Tube Active Noise Cancellation
Despite extensive mechanical decoupling, pressure waves and the rotating valves of the Pulse Tube (PT) cryocoolers remained a significant source of vibrational noise reaching the detector. To suppress this, an active noise cancellation technique was implemented to leverage destructive interference between the vibrations from the different PTs. The standard rotary valve motors were replaced with high-precision, low noise Linear Drives, which divide the rotational motion into 25,600 discrete steps per period. This allowed for continuous, milli-hertz scale frequency corrections (less than 20 mHz)#footnote[remove, "much finer control"?] to the valves, enabling a feedback loop to maintain finer control over small differences in fundamental frequencies of the active PTs in addition to their phases.

To find the best setup, an automated routine systematically scanned thousands of available relative phase configurations, assigning each a unique `phaseID`. For each configuration, the resulting vibrational noise—characterized by the PT fundamental frequency of 1.4 Hz and its first ten harmonics—was evaluated offline using the Average Noise Power Spectrum (ANPS) of the bolometers. Because the PT noise couples differently to every bolometer, the optimization algorithm iteratively targeted the specific subset of channels exhibiting the highest susceptibility to these vibrations. Upon identifying the optimal configuration that minimized the noise globally for the most affected channels, the continuous feedback loop locked the relative phases into this specific `phaseID` for the duration of the physics dataset.

==== Offline Denoising
While hardware optimizations and PT phase locking significantly reduced the baseline noise, a software-based denoising algorithm is applied offline to further attenuate residual seismic and microphonic noise. This mechanism utilizes auxiliary devices—such as accelerometers, seismometers, and microphones—that are sensitive to external vibrations and acoustic sources in the 0.1 Hz to 1 kHz range. The algorithm computes vector cross-spectral densities between each auxiliary device and each bolometer. While the bolometer noise spectra mirror the previously introduced ANPS, the auxiliary device data includes linear and quadratic time-domain terms to capture both capacitive pickup from cable vibrations and unipolar thermal responses in the calorimeters. These cross-spectral densities are used to construct a transfer function that predicts the bolometer noise based on the auxiliary outputs. The predicted noise is then subtracted in the time domain from the raw bolometer waveforms. Applied independently to each crystal for every run, this denoising technique significantly reduces both steady-state and transient noise, including residual PT harmonics and anthropogenic acoustic disturbances near the detector.

==== Cryostat Temperature Stabilization
Achieving optimal energy resolution over extensive data-taking campaigns demands highly stable detector operating conditions. Any thermal instabilities within the cryogenic system can propagate as temperature fluctuations in the bolometers, directly degrading the energy resolution. To compensate for these thermal drifts, a dedicated temperature control system based on a Proportional-Integral-Derivative (PID) loop was implemented on the 10 mK Mixing Chamber (MC) plate. The feedback loop utilizes a standard CUORE Neutron Transmutation Doped (NTD) germanium thermistor, which is affixed directly to the MC plate to serve as the input thermometer. Use of NTD as a temperature guage here was necessitated as the standard thermistor used for monitoring the absolute temperature of the MC, a Magnetic Field Fluctuation Noise Thermometer (MFFT-1) equipped with SQUIDs, requires averaging times on the order of minutes to achieve high precision, and was too slow to be used as an input for a real-time PID feedback loop.

Active stabilization is achieved by injecting a variable heat load into the MC plate to actively counteract temperature drops. This utilizes two standard silicon heaters (each with an intrinsic resistance of $R_h = 300 k Omega$) wired in parallel and bonded to the MC plate, controlled directly by the standard CUORE electronics#footnote[ref]. By regulating the PID target temperature slightly above the absolute minimum reachable by the Dilution Unit (e.g., stabilizing at $~ 11" mK"$ when the minimum is $~ 7" mK"$), the controller maintains sufficient thermal overhead to seamlessly inject heat and smooth out any transient thermal drifts.

==== Operating Temperature Scans

While the bolometric technique fundamentally benefits from lower temperatures—which dramatically increase the intrinsic thermal gain and maximize the Signal-to-Noise Ratio (SNR)—the optimal operating temperature is constrained by the electrical properties of the sensors. As the temperatures lower, the NTD base resistances climb exponentially. Even when properly biased, the resulting working point resistances ($R_"wp"$) can remain heavily mismatched with the readout electronics, which were nominally designed for an $R_"wp"$ of $~ 100 M Omega$. Operating at resistances in the tens of $G Omega$ severely limits the signal bandwidth due to higher $R_"bol" "/" R_L$ and higher parasitic capacitance#footnote[understand RLC characteristics related to this better], increasing the risk of electro-thermal instability#footnote[maybe add ref to load curves section that talk more about this?].

To precisely balance these competing factors, the collaboration executed a series of dedicated temperature scans in 2017, evaluating the detector response across a range of 9 mK to 27 mK. During the initial scans in mid-2017, data indicated that while lower temperatures yielded a strictly better SNR, the resulting NTD working resistances exceeded several $G Omega$s, placing them far outside the optimal design parameters. To guarantee operational stability and better impedance matching with the front-end electronics, a conservative compromise of 15 mK was selected for the initial 2017 data-taking campaigns, which included Datasets 3018 and 3021#footnote[didnt we replace the R_Ls at some point? should I add that here?].

In October 2017, a comprehensive temperature scan deploying the internal calibration sources (#tl208 and #ac228)#footnote[ref] was performed to directly evaluate the energy resolution on actual particle interactions. The analysis definitively proved that the gain in signal amplitude vastly outweighed the increase in baseline noise at lower temperatures, yielding an average energy resolution improvement of $\sim 15\%$ when dropping from 15 mK down to 11 mK#footnote['definitively'? -\_-, ref]. Consequently, for the bulk of the CUORE physics data used for the M2 analysis discussed in @chap6 commencing in 2018, the operational base temperature was officially lowered to 11 mK#footnote[data used in this analysis, later we moved back to 15mK]. To safely manage the higher NTD working resistances—which averaged between $0.6$ and $1.2 G Omega$ at 11 mK—the automated Working Point algorithm was upgraded to explicitly monitor the pulse shapes and proactively avoid complex pulse deformations#footnote[I.N thesis p81].

=== Load Curves and Working Point Optimization

The primary objective of detector optimization is to maximize the Signal-to-Noise Ratio (SNR) by determining the precise, optimal bias current ($I_"B"$) for each individual NTD. The NTD thermistors are biased via low-noise, room-temperature load resistors ($R_"L"$)#footnote[didn't we replace these midway? maybe mention that and the reasons? -- higher than expected NTD resistances? lower than expected doping?]. The resulting voltage signals are amplified by approximately 5000 V/V before being digitized by the Data Acquisition (DAQ) system. Howevr, because of electro-thermal feedback, the current-voltage (I-V) relationship of the bolometers can be highly non-linear. The NTD resistance ($R_"NTD"$) drops steeply as a function of temperature according to the Variable Range Hopping model: $R = R_0 e^(T_0"/"T)^gamma$. Simultaneously, the Joule power dissipated across the NTD by the bias current is given by:

$ P = I_"B"^2 R_"NTD" = (V_B - V_"NTD")^2 / R_L^2 dot R_"NTD" $
resulting an increase in NTD temperature ($T_"NTD"$),
$ T_"NTD" - T_0 = Delta T = P"/"G $
At lower biases, an increase in bias voltage $V_B$ results in a stronger resistance drop compared to the increased bias current, thus lowering the power dissipation as the NTD temperature rises reaching another steady state with higher $T_"NTD"$, $V_"NTD"$ and $I_B$ . At high bias voltages, the higher steady state power dissipation results in higher NTD temperature, and pushing $V_B$ past a certain point triggers a thermal run-away regime where the resistance decrease can no longer counter the increased $I_"B"$, thus continually increasing the power dissipation without any increase in $V_"NTD"$ or $V_B$. In this regime the thermistor's dynamic resistance is negative, and operating near this non-ohmic inversion point severely compromises detector stability. Additionally, the long cables connecting the cryogenic NTDs to the room-temperature preamplifiers introduce parasitic capacitance#footnote[I.N thesis p54 ~500pF]. This forms an LC-oscillator with the parasitic capacitance, causing undamped voltage swings of several volts that render the channel unusable and induce severe crosstalk in neighboring detectors. Therefore, the optimal Working Point (WP) must be carefully chosen to maximize the SNR while guaranteeing strict electro-thermal stability safely below the inversion point.

==== Load Curve Measurements

The optimal bias parameters are derived empirically through load curve measurements. At a stable base temperature, the bias voltage is systematically swept from zero to a few milli volts#footnote[ref? mV, correct?]. To accurately measure the voltage drop across the bolometer ($V_"NTD"$) without being biased by unknown preamplifier offsets, the measurement is taken at both negative and positive polarities for each voltage step. The true bolometer voltage is extracted as $V_"NTD" = (V^+_"out" - V^-_"out") / (2G)$. During each step, multiple reference heater pulses are injected, to optimize the detector both at higher eneries (e.g., 7 MeV) #footnote[Using only high energy pulses was found to mask pulse-shape deformations that severely affect lower energies.] as well as the lower (~800 keV or 1 MeV), to ensure uniform stability across the Region of Interest. For each channel, a standard set of diagnostic curves is constructed as a function of $I_B$:
+ Pulse Amplitude ($A$) vs. $I_"B"$ (evaluated using an Average Pulse to cancel out random noise),
+ Baseline Noise RMS vs. $I_"B"$ (evaluated using optimally filtered waveforms),
+ SNR vs. $I_B$,
+ and $V_"NTD"$ vs. $I_B$ (the static load curve, used to identify the inversion point).

==== Automated Working Point Selection

Due to the massive scale of CUORE (988 channels), identifying the optimal WP is performed by a dedicated automated algorithm rather than manual inspection. Because raw RMS curves (and consequently SNR curves) can be jagged due to statistical noise fluctuations, the algorithm first smoothes the RMS curve by performing a robust linear fit of the RMS against the bolometer resistance ($R_"NTD"$), operating under the assumption that thermal Johnson noise dominates. The algorithm automatically filters out outlier points (fake maxima) caused by coincident particle events or amplitude reconstruction failures. The optimal $V_B$ is provisionally identified at the maximum of the smoothed SNR curve.

*Pulse Shape Validation:* To guarantee the channel is not dangerously close to the inversion point, the algorithm explicitly checks the shape of the average pulse at the selected WP. Deformations are identified by counting the number of flexes in the discrete second derivative of the pulse or by fitting the pulse to a transfer function and evaluating the ratio of real to imaginary poles. If the pulse exhibits ringing or deformation, the algorithm iteratively steps back to lower bias voltages until a stable pulse shape is recovered. For the approximately 30 channels with non-functioning heaters where SNR cannot be evaluated, the algorithm defaults to a conservative bias voltage (typically ~3 V)#footnote[ref: LM thesis p74] to prevent any risk of oscillation and subsequent crosstalk.
