#import "../common.typ": *

== Low-Level Processing & Event Reconstruction

Once stable operating conditions are established, the CUORE detector functions as an exceptionally quiet measurement apparatus. Extracting physical event properties from the continuous data stream, however, requires a multi-stage software reconstruction pipeline. This process transitions from basic pulse triggering to extraction of pulse shape parameters, and ultimately, to the precise estimation of the deposited energy. CUORE employs a two-tiered data processing strategy. First, a real-time data production pipeline is executed online as the continuous waveforms are acquired. This fast online framework utilizes a standard derivative trigger to monitor detector stability and assess the accumulation of statistics during calibration runs.

Conversely, the final physics analysis relies on a much more sophisticated offline processing pipeline. The offline analysis processes data in discrete temporal units called *datasets*—each consisting of a central physics run bracketed by initial and final calibration runs—to leverage similar thermodynamic conditions and maximize statistics. During this offline phase, the raw continuous data is re-evaluated using advanced algorithms. These comprehensive steps include the implementation of an optimal filter-based trigger to lower energy thresholds, precise thermal gain stabilization to correct for minute temperature drifts over the dataset's duration, rigorous energy estimation based on optimally filtered pulse amplitudes, and concident event analysis to detect multi-site events.


=== Data Collection

The acquisition of continuous data in CUORE is systematically organized into discrete periods called datasets. A dataset comprises a collection of daily runs—each lasting $~ 24 "hrs"$—during which the detector's cryogenic and electronic operating conditions remain highly stable and consistent. These runs are primarily categorized as either physics runs or calibration runs. Physics runs record the natural background radioactivity and provide the actual data used for the final rare-event analysis. In contrast, calibration runs involve the insertion of external radioactive sources into the cryostat to accurately characterize the detector's energy response. A single dataset generally spans a continuous duration of one to two months and is strictly bracketed by calibration campaigns at both its beginning and end to monitor any long-term drifts. In addition to these primary data-taking modes, dedicated optimization runs—such as those required to measure bolometer load curves and adjust pulse tube phases—are periodically executed between physics data collection campaigns to guarantee optimal detector performance.

=== Data Processing Pipeline<sec4.2-pipeline>
Although CUORE records continuous waveforms, the data is ultimately analyzed through an event-based processing pipeline. This pipeline relies on Diana, a custom software framework built upon CERN's ROOT C++ libraries. Evolving from the earlier CUORECINO and CUORE-0 experiments, Diana operates using a flexible architecture of pluggable modules that act selectively on specific branches within a ROOT data tree. These modules vary in complexity, ranging from simple event filters—such as isolating noise triggers—to sophisticated routines like Principal Component Analysis. To form a complete analysis chain, these modules are sequentially arranged into configurations called sequences. The exact parameters and order of these sequences are stored in configuration files, which are strictly tagged and archived to ensure that the processing of any specific data release can be perfectly replicated in the future.

Within this framework, a single CUORE event is defined as an independent 10-second waveform window. The window is anchored by a trigger, capturing 3 seconds of pre-trigger baseline and 7 seconds of post-trigger data. During the initial preprocessing sequence, basic pulse parameters—such as the baseline voltage, baseline slope, and root-mean-square (RMS) noise—are calculated. This first sequence is also responsible for applying essential data quality filters, which include rejecting manually flagged bad intervals and enforcing basic multi-trigger and dead-time cuts.

As the continuous data stream is parsed, the Data Acquisition (DAQ) system classifies the triggered events into three primary categories: noise, heater, and signal events. Noise events are randomly triggered baseline samples, while heater events are explicitly flagged by the DAQ when the control system fires a Joule heater. Signal events encompass all other triggers, representing genuine thermal depositions in the crystal. These categorizations are vital for constructing the optimal filter. Specifically, clean signal triggers are aligned, scaled and averaged to build the *Average Pulse* (AP), which represents the standard thermal response of the detector to radioactive energy depositions. Conversely, flat noise triggers are used to calculate the *Average Noise Power Spectrum* (ANPS)#footnote[do we need to make these, AP/ANPS more explicit?]. Because operating conditions can vary slightly, both the AP and ANPS are constructed individually for every bolometer channel in each run. Armed with these baseline templates, subsequent sequences can accurately calculate pulse amplitudes, apply thermal gain stabilization, calibrate the energies, and ultimately proceed to coincidence detection and pulse shape analysis.

=== Triggering

Triggering is the fundamental first step in data processing, identifying discrete energy depositions within the continuous data stream. Upon detection, events are classified as signal, noise, or reference pulser events#footnote[reword? pulsers are tagged, not triggred per se], and saved as timestamps referring to waveform windows. Reflecting CUORE's extremely low background environment, the standard physics trigger rate is roughly 1 mHz per channel. During calibration campaigns, this increases to 30–50 mHz depending on the bolometer's proximity to the external sources.

The Apollo data acquisition framework utilizes a Derivative Trigger (DT) for real-time online monitoring. The DT is a fast, computationally efficient algorithm that evaluates the slope $ d V"/"d t$ of the last $40"ms"$ of the waveform against channel-specific threshold determined during the initial Working Point optimization. While effective for basic operation and diagnostics, rare low-energy phenomena demand significantly higher sensitivity. To achieve this, the continuous data files are re-processed entirely offline using an Optimum Trigger (OT) algorithm.

=== Optimum Filter

The offline Optimum Trigger relies on the Optimum Filter (OF), a mathematical technique designed to maximize the Signal-to-Noise Ratio (SNR) for a given signal profile. By selectively suppressing background noise frequencies, the OF enables lower trigger threshold. This increases the detection efficiency for low-energy pulses and improves the accuracy of both energy reconstruction and coincidence analysis—which is critical for isolating the single-site (Multiplicity 1) events required for the $0 nu beta beta$ search.

Constructing the OF requires the run and channel specific AP and ANPS built using the initial DT-flagged data. Using the AP signal $S(omega)$ and the noise spectrum $N(omega)$, the optimal transfer function $H(omega_k)$ is defined in the frequency domain as:

$ H(omega_k) = (S^*(omega_k)) / N(omega_k) e^(-i omega_k t_"max") $

Here, $S^*(omega_k)$ is the complex conjugate of the signal's Fourier transform. The exponential phase factor acts as a time-translation operator, deliberately shifting the peak of the filtered pulse to a designated time index, $t_"max"$, within the sampling window. This phase shift compensates for inherent trigger time jitters, perfectly aligning all filtered pulses in the time domain so that their maximum amplitudes—the basis for the final energy estimator—can be reliably and accurately evaluated.

=== Pulse Amplitude
Following event triggering, precise reconstruction of the pulse amplitude serves as the primary metric for calculating the deposited energy. Because the bolometric thermal response depends on the instantaneous baseline temperature, the raw amplitude is modeled as $A(E,T) = a(E) dot G(T)$. This parameterization explicitly separates the intrinsic energy-dependent amplitude, $a(E)$, from the temperature-dependent thermal gain, $G(T)$.

To extract the final pulse amplitude, the algorithm applies the previously constructed Optimum Filter and identifies the maximum of the resulting waveform in the time domain. To overcome the resolution limits imposed by the discrete sampling rate, this maximum is calculated using localized polynomial interpolation—typically a 3-point or 5-point#footnote[which?] parabolic fit around the peak sample—yielding a highly precise, sub-sample amplitude estimator.

=== Stabilization

Thermal Gain Stabilization (TGS) is designed to correct the extracted pulse amplitudes for long-term baseline temperature drifts. The amplitude of an events at constant energy is modeled as a scaling of $a_E$,
$ A_E (t) = a_E (t) dot (p_1 + p_2 dot b(T)) $
where the baseline $b(T)$ acts as a proxy for the event's baseline temperature, and hence the temperature dependant detector response. The CUORE analysis pipeline utilizes two independent TGS algorithms processed in parallel: Heater TGS and Calibration TGS. The Heater TGS method continuously tracks the amplitude variations of periodic pulser events, which inject a highly stable, constant reference energy directly into the crystals. Alternatively, the Calibration TGS method tracks the position of a prominent, naturally occurring background peak—typically the 2615 keV line from #tl208—across the physics data as the constant energy proxy event. After fitting for $p_1, p_2$ from these events, we can correct arbitrary pulse amplitudes to stabilize them against the temperature fluctuations. To account for sudden operational breaks or sharp temperature variations that can occur within a single dataset, the stabilization parameters are calculated over discrete, dynamically defined time steps where necessary.

- Add more about calibration TGS,
- Is this correct? " To accurately account for nonlinearities in the gain-temperature dependence, this calibration-based method incorporates a dataset-dependent offset voltage derived directly from the empirical working point."

=== Energy Calibration

Following stabilization, the energy calibration procedure converts the stabilized pulse amplitudes into actual physical energy values by anchoring them to known gamma-ray emission lines. This critical mapping relies on dedicated calibration runs performed at the boundaries of the dataset, during which the detector array is exposed to externel sources. The internal strings of the Detector Calibration System (DCS) deployed #th232 and #ac228 sources directly among the inner towers initially, while later datasets utilized the external sources with #th232 and #co60 as described in @sec3.4-calib.

For each bolometer channel, a stabilized amplitude histogram is generated, and an automated peak-finding algorithm identifies prominent reference peaks and evaluate their exact positions by fitting a gaussian coupled with a first degree polynomial background#footnote[validate! the 1-ton-yr paper refers to Q0 paper which claims this.] . For the first datasets with internal calibration system, these peaks included a multitude of gamma lines coming from a cascade of decays (#super[212]Pb \@239, #super[228]Ac \@338, #tl208 \@239, #super[228]Ac \@911, #super[222]Ac \@969, #tl208 \@2615). However, with the EDSC the low energy gammas are highly attenuated, and only the peaks at 511 keV and 2615 keV were usable from the #th232 source. This made our calibration procedure 'blind' to a large part of the energy range that included the 0#nbb ROI around 2528 keV. Adding the #co60 from the 4th dataset onward partially mitigated this problem, providing us with additional peaks from the $gamma$s at 1173 keV and 1333 keV.

The final calibration function is derived by fitting the true physical energies of these reference peaks against their reconstructed stabilized amplitudes using a second-order polynomial with a zero intercept. In instances where automatic fits fail—usually due to low statistics or poor baseline resolution—the calibration parameters for those specific calorimeters are corrected manually.#footnote[add the fit functions for calibration curve as well as the peak functions]

=== Energy Estimator

Because the Heater and Calibration stabilization methods are processed simultaneously, the resulting dataset yields two distinct energy estimates for every triggered event after the calibration modules. An automated selection algorithm is employed to identify the superior energy estimator for each individual channel based on their resolution. The selection process evaluates a Figure of Merit (FOM) based on the peak resolution and overall position stability. Specifically, the algorithm calculates a comparison ratio, $ W = alpha (C_h^2 / sigma_h^2) "/" (C_c^2 / sigma_c^2) $, which evaluates the stability constants ($C$) and resolutions ($sigma$) between the heater ($h$) and calibration ($c$) variables.

A Fisher test statistic, $F(W)$, is then evaluated against this ratio. If $W < 1$ and the sample size satisfies the statistical threshold for $alpha = 0.2$, the Calibration TGS is deemed superior and is chosen for that specific channel. If these conditions are not met, the Heater TGS is applied by default. Historically, across typical CUORE physics runs, this statistical threshold leads to the Calibration TGS being selected for approximately 100 channels (which includes the 29 channels without a functioning heater) ensuring that the most stable and precise energy estimator is universally applied across the array.


=== Multiplicity

Once the energy of each individual trigger is precisely determined, the final step in the event reconstruction pipeline is to evaluate the temporal correlations between these triggers across the entire detector array. Identifying coincident events is crucial for characterizing the background and significantly enhancing the sensitivity of the $0 nu beta beta$ search. Because approximately 88% of $0 nu beta beta$ decays are expected to deposit their full energy within a single crystal, they register as single-crystal (Multiplicity 1, or M1) events. Consequently, applying a strict anti-coincidence cut strongly suppresses background contributions from multi-site gamma interactions and degraded surface alphas.

To successfully implement this cut, the coincidence window must be kept strictly narrow to minimize accidental random coincidences. To properly define this coincidence window, denoted as $Delta t^*$, the characteristic time response of each detector must be individually calibrated. Because individual bolometers operate at slightly different baseline temperatures, their signal rise times vary naturally, introducing a channel-dependent time delay ($t_"delay"$). The absolute delay for each channel is evaluated relative to a globally defined reference channel. This is achieved by first calculating the relative time delays between physically adjacent crystal pairs using known coincident background events—such as the 2615 keV peak from the gamma cascade—or high-statistics pulser events. By iteratively summing these relative delays across the detector network, the absolute temporal error is minimized, and the array's timing response is fully normalized.

After applying the precise timing correction ($Delta t^* - Delta t$), events are grouped into multiplets and stored alongside their corresponding multiplicity, channel-dataset identifiers, synchronized timestamps, individual component energies, total deposited energy, and time-ordering indices. For the standard 1 ton-yr $0 nu beta beta$ analysis, a dynamic "running window" of 10 ms is utilized to maximize signal efficiency, alongside a spatial distance cut of 150 mm and a universal array-wide energy threshold of 40 keV. Conversely, different physics searches require tailored coincidence parameters. The Background Model (BM), for instance, employs a wider 60 ms coincidence window to ensure the accurate spectral grouping of higher-energy coincident events. Meanwhile, specific low-energy analyses, such as Dark Matter or axion searches below 100 keV, rely on the channel-dependent thresholds established directly by the Optimum Trigger rather than a universal energy cut.

=== Pulse Shape Analysis
Following the isolation of single-crystal events through coincidence analysis, it is imperative to verify that the individual waveforms comprising these events are genuinely physical. Pulse Shape Analysis (PSA) is utilized as a critical discrimination tool to identify and remove atypical waveforms, such as pile-up events or spurious unphysical electronic noise. For each recorded event, the digitized pulse vector $arrow(v)$ is compared against its corresponding channel-specific Average Pulse template, $arrow(v)_"AP"$. The morphological deviation between the measured pulse and the template is quantified by a metric known as the Reconstruction Error (RE), defined mathematically as:

$"RE" = sqrt(sum_(d=1)^D (v_i - (arrow(v) dot arrow(v)_"AP") / (v_"AP,i") )^2 )$

Because the bolometer's thermal response inherently scales with the deposited energy, the RE exhibits a natural energy dependence. For valid physical events spanning the range of 100 keV to 2615 keV, this energy dependence is empirically modeled by fitting a second-order polynomial, $f(E)$, to the primary signal band. To standardize this metric across the entire detector array and compensate for channel-to-channel variations, a Normalized Reconstruction Error (NRE) is computed as:

$"NRE" = ("RE" - f(E)) / "MAD"(E)$

where $"MAD"(E)$ represents the median absolute deviation of the polynomial fit. The final acceptance threshold on the NRE is established by systematically maximizing a Figure of Merit, defined as $"FOM" = epsilon / sqrt(epsilon_"bkg")$, where $epsilon$ and $epsilon_"bkg"$ denote the signal and background acceptance efficiencies, respectively. To rigorously prevent statistical bias or over-tuning during this tuning phase, the threshold optimization is performed using only a randomly selected half of the dataset.

With the physical parameters fully evaluated and the low-level data quality cuts strictly established, the surviving dataset is thoroughly calibrated and reconstructed. However, before any final spectral fits can be performed to extract the decay rate, a stringent data blinding procedure must be implemented to protect the region of interest, as detailed in Section 4.3.
