#import "../common.typ": *

== Low-Level Processing & Event Reconstruction

Once stable operating conditions are established, the CUORE detector functions as an exceptionally quiet measurement apparatus. Extracting physical event properties from the continuous data stream, however, requires a multi-stage software reconstruction pipeline. This process transitions from basic pulse triggering to the extraction of pulse shape parameters, and ultimately, to the precise estimation of the deposited energy. CUORE employs a two-tiered data processing strategy. First, a real-time data production pipeline is executed online as the continuous waveforms are acquired. This fast online framework utilizes a standard derivative trigger to monitor detector stability and assess the accumulation of statistics during calibration runs.

Conversely, the final physics analysis relies on a much more sophisticated offline processing pipeline. The offline analysis processes data in discrete temporal units called *datasets*—each consisting of a central physics run bracketed by initial and final calibration runs—to leverage similar thermodynamic conditions and maximize statistics. During this offline phase, the raw continuous data is re-evaluated using advanced algorithms. These comprehensive steps include the implementation of an optimal filter-based trigger to lower energy thresholds, precise thermal gain stabilization to correct for minute temperature drifts over the dataset's duration, rigorous energy estimation based on optimally filtered pulse amplitudes, and concident event analysis to detect multi-site events.


=== Triggering


==== Analysis Event

- CUORE event is a 10s waveform with a trigger, 3s before the trigger and 7s after, sampled at 1000Hz.
- As mentioned earlier, the DAQ triggers two kinds of events, signal and noise, and the heater events are also recorded by the DAQ as they are triggered by the heaters.
  - Noise are randomly triggered samples,
  - Heater events are recorded by the DAQ as it is signalled from the heaters,
  - Signal are the expected thermal events that are not heaters.

Triggering is the fundamental first step in data processing, responsible for identifying discrete energy depositions within the continuous data stream. Upon detection, events are classified as signal, noise, or reference pulser events, with each triggered event being saved as an independent 10-second waveform window. The extremely low background environment of CUORE is reflected in the trigger rates: during standard physics runs, the background event rate is roughly 1 mHz per channel. During calibration campaigns, this rate increases significantly to 30–40 mHz (typically ranging from 10–20 mHz for inner tower bolometers to 40–50 mHz for those on the outer edges facing the calibration strings).

The primary online trigger utilized by the Apollo data acquisition framework is the Derivative Trigger (DT). The DT is a fast, computationally efficient algorithm that evaluates the slope of the waveform averaged over a defined number of samples. It operates using channel-specific parameters—such as the derivative threshold, debounce time, and dead-time—which are empirically determined during the initial Working Point optimization. While the DT serves as an excellent tool for real-time monitoring, rare low-energy phenomena demand significantly higher sensitivity. To achieve this, the continuous data files are re-processed entirely offline using the Optimum Trigger (OT) algorithm.

The OT relies on an Optimum Filter (OF), a mathematical technique theoretically designed to maximize the Signal-to-Noise Ratio (SNR) of a specific signal profile against a known background noise profile. By applying this filter, the OT suppresses specific noise frequencies, enabling a dramatically lower trigger threshold. This not only increases the detection efficiency for low-energy pulses but also improves the accuracy of the energy reconstruction and the subsequent coincidence analysis, which is critical for identifying single-site (Multiplicity 1) events for the main $0\nu\beta\beta$ analysis, as well as multi-site events for the Background Model.

Constructing the Optimum Filter requires two channel-specific components: an Average Pulse (AP) to model the expected signal response, and an Average Noise Power Spectrum (ANPS) to model the baseline noise. Both components are generated per dataset using the data initially flagged by the online DT. The AP is constructed by aligning and averaging the scaled waveforms from hundreds of high-quality calibration pulses, while the ANPS is computed by calculating the spectral density histogram in Fourier space from randomly triggered baseline noise windows. Using the AP signal $S(omega)$ and the noise spectrum $N(omega)$, the optimal transfer function $H(omega_k)$ for a given bolometer is defined in the frequency domain as:

$H(omega_k) = (S^*(omega_k)) / N(omega_k)  e^(-i omega_k t_"max")$

Here, $S^*(omega_k)$ is the complex conjugate of the signal's Fourier transform. The exponential phase factor, $e^(-i omega_k t_"max")$, acts as a time-translation operator. It is introduced to explicitly shift the peak of the filtered pulse to a designated time index, $t_"max"$, within the sampling window. This phase shift critically compensates for inherent trigger time jitters, ensuring that all filtered pulses are perfectly aligned in the time domain, allowing the maximum amplitude of the pulse—which serves as the basis for the final energy estimator—to be evaluated reliably.

=== Data Collection

The acquisition of continuous data in CUORE is systematically organized into discrete periods called datasets. A dataset comprises a collection of daily runs—each lasting $~ 24 "hrs"$—during which the detector's cryogenic and electronic operating conditions remain highly stable and consistent. These runs are primarily categorized as either physics runs or calibration runs. Physics runs record the natural background radioactivity and provide the actual data used for the final rare-event analysis. In contrast, calibration runs involve the insertion of external radioactive sources into the cryostat to accurately characterize the detector's energy response. A single dataset generally spans a continuous duration of one to two months and is strictly bracketed by calibration campaigns at both its beginning and end to monitor any long-term drifts. In addition to these primary data-taking modes, dedicated optimization runs—such as those required to measure bolometer load curves and adjust pulse tube phases—are periodically executed between physics data collection campaigns to guarantee optimal detector performance.

=== Pulse Amplitude

Following event triggering, the precise reconstruction of the pulse amplitude serves as the primary metric for calculating the final deposited energy. Because the bolometric thermal response exhibits a measurable dependence on the instantaneous baseline temperature, the raw pulse amplitude is phenomenologically modeled as $A(E,T) = a(E) dot G(T)$. This parameterization explicitly separates the intrinsic energy-dependent amplitude, $a(E)$, from the temperature-dependent thermal gain, $G(T)$. Before this final amplitude can be accurately evaluated, the raw waveform undergoes a pre-processing stage to extract basic pulse characteristics. These parameters include the pre-trigger baseline (evaluated over the initial 0 to 2.25 seconds of the acquired window), the baseline slope, the baseline RMS noise, and the total number of distinct triggered pulses within the window. Strict data quality cuts are then applied based on these parameters to isolate clean, single-pulse events, which are essential for constructing the Optimum Filter (OF).

The Optimum Filter is a mathematical technique designed to maximize the signal-to-noise ratio by optimally weighting the frequency components of the signal against the intrinsic background noise. In the frequency domain, the resulting filtered waveform is proportional to $S(omega) / |N(omega)|^2 e^(-i omega t_"max")$, where $S(omega)$ represents the ideal signal template and $N(omega)$ represents the measured noise power spectrum. To extract the final pulse amplitude, the algorithm identifies the maximum of this optimally filtered waveform in the time domain. To avoid limitations imposed by the discrete sampling rate, this maximum is evaluated using a localized polynomial interpolation—typically a 3-point or 5-point parabolic fit around the peak sample—yielding a highly precise, sub-sample amplitude estimator.

=== Stabilization

Thermal Gain Stabilization (TGS) is an essential post-processing step designed to correct the extracted pulse amplitudes for long-term baseline temperature drifts. To account for sudden operational breaks or sharp temperature variations that can occur within a single dataset, the stabilization parameters are calculated over discrete, dynamically defined time steps. The CUORE analysis pipeline utilizes two independent TGS algorithms processed in parallel: Heater TGS and Calibration TGS. The Heater TGS method continuously tracks the amplitude variations of periodic pulser events, which inject a highly stable, constant reference energy directly into the crystals. The thermal response of these pulser events is modeled as $A_h (t) = a_h(E) dot (p_1 + p_2 dot T + ...)$, where the variable $T$ acts as a proxy for the instantaneous baseline temperature. Alternatively, the Calibration TGS method tracks the position of a prominent, naturally occurring background peak—typically the 2615 keV line from #tl208—across the physics data. To accurately account for nonlinearities in the gain-temperature dependence, this calibration-based method incorporates a dataset-dependent offset voltage derived directly from the empirical working point.

=== Energy Calibration

Following stabilization, the energy calibration procedure converts the stabilized pulse amplitudes into actual physical energy values by anchoring them to known gamma-ray emission lines. This critical mapping relies on dedicated calibration runs performed at the boundaries of the dataset, during which the detector array is exposed to $232$Th and $60$Co sources. The internal strings of the Detector Calibration System (DCS) deploy these sources directly among the inner towers, while supplementary external sources are utilized to ensure uniform radiation coverage for the outermost towers.

For each bolometer channel, a stabilized amplitude histogram is generated, and an automated peak-finding algorithm identifies prominent reference peaks characterized by high signal-to-noise ratios. Each identified peak is then carefully fitted using an empirical line shape model, typically comprising a combination of a Gaussian and a Crystal Ball function (or an asymmetric Gaussian core). Concurrently, the underlying background continuum is modeled using a first-order polynomial combined with a smoothed step function to accurately replicate the Compton edge. The final calibration function is derived by fitting the true physical energies of these reference peaks against their reconstructed stabilized amplitudes using a second-order polynomial with a zero intercept. In instances where automatic fits fail—usually due to low statistics or poor baseline resolution—the calibration parameters for those specific calorimeters are corrected manually to ensure maximum data retention.

=== Energy Estimator

Because the Heater and Calibration stabilization methods are processed simultaneously, the resulting dataset yields two distinct energy estimates for every triggered event. To resolve this redundancy and maximize resolution, an automated selection algorithm is employed to identify the superior energy estimator for each individual channel. The selection process evaluates a Figure of Merit (FOM) based on the peak resolution and overall position stability. Specifically, the algorithm calculates a comparison ratio, $W = alpha (C_h^2 / sigma_h^2) / (C_c^2 / sigma_c^2)$, which evaluates the stability constants ($C$) and resolutions ($sigma$) between the heater ($h$) and calibration ($c$) variables.

A Fisher test statistic, $F(W)$, is then evaluated against this ratio. If $W < 1$ and the sample size satisfies the statistical threshold for $alpha = 0.2$, the Calibration TGS is deemed superior and is chosen for that specific channel. If these conditions are not met, the Heater TGS is applied by default. Historically, across typical CUORE physics runs, this strict statistical threshold leads to the Calibration TGS being selected for approximately 100 channels, ensuring that the most stable and precise energy estimator is universally applied across the array.


=== Multiplicity

Once the energy of each individual trigger is precisely determined, the final step in the event reconstruction pipeline is to evaluate the temporal correlations between these triggers across the entire detector array. Identifying coincident events is crucial for characterizing the background and significantly enhancing the sensitivity of the $0 nu beta beta$ search. Because approximately 88% of $0 nu beta beta$ decays are expected to deposit their full energy within a single crystal, they register as single-crystal (Multiplicity 1, or M1) events. Consequently, applying a strict anti-coincidence cut strongly suppresses background contributions from multi-site gamma interactions and degraded surface alphas.

To successfully implement this cut, the coincidence window must be kept strictly narrow to minimize accidental random coincidences. To properly define this coincidence window, denoted as $Delta t^*$, the characteristic time response of each detector must be individually calibrated. Because individual bolometers operate at slightly different baseline temperatures, their signal rise times vary naturally, introducing a channel-dependent time delay ($t_"delay"$). The absolute delay for each channel is evaluated relative to a globally defined reference channel. This is achieved by first calculating the relative time delays between physically adjacent crystal pairs using known coincident background events—such as the 2615 keV peak from the gamma cascade—or high-statistics pulser events. By iteratively summing these relative delays across the detector network, the absolute temporal error is minimized, and the array's timing response is fully normalized.

After applying the precise timing correction ($Delta t^* - Delta t$), events are grouped into multiplets and stored alongside their corresponding multiplicity, channel-dataset identifiers, synchronized timestamps, individual component energies, total deposited energy, and time-ordering indices. For the standard 1 ton-yr $0 nu beta beta$ analysis, a dynamic "running window" of 10 ms is utilized to maximize signal efficiency, alongside a spatial distance cut of 150 mm and a universal array-wide energy threshold of 40 keV. Conversely, different physics searches require tailored coincidence parameters. The Background Model (BM), for instance, employs a wider 60 ms coincidence window to ensure the accurate spectral grouping of higher-energy coincident events. Meanwhile, specific low-energy analyses, such as Dark Matter or axion searches below 100 keV, rely on the channel-dependent thresholds established directly by the Optimum Trigger rather than a universal energy cut.

=== Pulse Shape Analysis
Following the isolation of single-crystal events through coincidence analysis, it is imperative to verify that the individual waveforms comprising these events are genuinely physical. Pulse Shape Analysis (PSA) is utilized as a critical discrimination tool to identify and remove atypical waveforms, such as pile-up events or spurious unphysical electronic noise. For each recorded event, the digitized pulse vector $arrow(v)$ is compared against its corresponding channel-specific Average Pulse template, $arrow(v)_"AP"$. The morphological deviation between the measured pulse and the template is quantified by a metric known as the Reconstruction Error (RE), defined mathematically as:

$"RE" = sqrt(sum_(d=1)^D (v_i - (arrow(v) dot arrow(v)_"AP") / (v_"AP,i") )^2 )$

Because the bolometer's thermal response inherently scales with the deposited energy, the RE exhibits a natural energy dependence. For valid physical events spanning the range of 100 keV to 2615 keV, this energy dependence is empirically modeled by fitting a second-order polynomial, $f(E)$, to the primary signal band. To standardize this metric across the entire detector array and compensate for channel-to-channel variations, a Normalized Reconstruction Error (NRE) is computed as:

$"NRE" = ("RE" - f(E)) / "MAD"(E)$

where $"MAD"(E)$ represents the median absolute deviation of the polynomial fit. The final acceptance threshold on the NRE is established by systematically maximizing a Figure of Merit, defined as $"FOM" = epsilon / sqrt(epsilon_"bkg")$, where $epsilon$ and $epsilon_"bkg"$ denote the signal and background acceptance efficiencies, respectively. To rigorously prevent statistical bias or over-tuning during this tuning phase, the threshold optimization is performed using only a randomly selected half of the dataset.

With the physical parameters fully evaluated and the low-level data quality cuts strictly established, the surviving dataset is thoroughly calibrated and reconstructed. However, before any final spectral fits can be performed to extract the decay rate, a stringent data blinding procedure must be implemented to protect the region of interest, as detailed in Section 4.3.
