= Data Taking and Processing <chap:4>

Operating the CUORE detector requires a comprehensive suite of optimization procedures to ensure the highest quality data prior to and during data collection. These optimization steps range from incremental hardware improvements, such as the mechanical isolation of external noise sources, to periodic tuning procedures, like the active cancellation of pulse tube noise through phase adjustments. To guarantee highly stable operating conditions over long periods, the overall data collection timeline is strategically segmented into distinct campaigns referred to as datasets. Each dataset consists of a central, undisturbed physics run—during which the detector operates under stable conditions and is exposed strictly to natural background radioactivity. These physics runs are bracketed at both the beginning and the end by dedicated periods of detector optimization and energy calibration, ensuring the detector's response is well-characterized throughout the campaign.

The evaluation of this data occurs in two distinct phases: an online diagnostic phase and an offline precision phase. As data is collected, it undergoes a real-time processing pipeline designed primarily for continuous detector monitoring. This online framework performs basic triggering, extracts preliminary pulse characteristics, and generates diagnostic energy spectra utilizing the initial calibration settings acquired at the start of the run. However, the final physics results rely on a much more rigorous offline post-processing of each completed dataset. This comprehensive re-processing implements optimal derivative triggering, advanced pulse shape analysis, and precise thermal gain stabilization that leverages the calibration data from both ends of the dataset to account for temporal drifts. Once the accurate energy and timing of each event are reconstructed, a coincidence analysis is performed to evaluate event multiplicity, isolating the single-crystal (multiplicity 1) events. Finally, a blinded fit is applied to the resulting energy spectrum in the region of interest to extract the 0νββ decay rate without introducing analyst bias.

#include "040-data/041-optimization.typ"

#include "040-data/042-basic_processing.typ"

// #include "040-data/043-post_processing.typ"
